index: 1

hyperparameters:
  batch_size: 10
  obstacle_clearance:
    range: [0., 0.]
  obstacle_expansion:
    isr1: [150, 255]
    val1: [0.4, 0.4]
    isr2: [20, 150]
    val2: [0.4, 0.]
    isr3: [0, 20]
    val3: [0., 0.]
  guidance_method: 'iv' # 'iv': intersection_volume; 'sv': swept_volume
  grad_norm: True
  
  guidance_schedule:
    type: 'constant' # 'constant' or 'varying' (1.4 + (t/self.T))
    scale_val: 0.05 # Value used to scale the gradients (if type=='constant')
  volume_trust_region: 0.0008 # 0.001


