index: 10

hyperparameters:
  batch_size: 10
  obstacle_clearance:
    range: [0.06, 0.06] # linearly increasing
  obstacle_expansion:
    isr1: [80, 255]
    val1: [0.4, 0.4]
    isr2: [20, 80]
    val2: [0.0, 0.0]
    isr3: [0, 20]
    val3: [0., 0.]
  guidance_method: 'sv' # 'iv': intersection_volume; 'sv': swept_volume
  grad_norm: False
  
  guidance_schedule:
    type: 'varying' # 'constant' or 'varying' (1.4 + (t/self.T))
    scale_val: 0.05 # Value used to scale the gradients (if type=='constant')
  volume_trust_region: 0.0008 # 0.001


